In [ ]:
#作業目標
#活用矩陣運算，實做線性代數
#作業重點
#線性代數公式應用
#矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

#題目:
#array1 = np.array([[10, 8], [3, 5]])

#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#運用上列array計算特徵值、特徵向量?
#運用上列array計算SVD?

In [2]:
import numpy as np

In [9]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

array2 = np.linalg.inv(array1)
array2

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [10]:
array3 = np.matmul(array1, array2)
array3

array([[1., 0.],
       [0., 1.]])

In [11]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array2)
w


array([0.07692308, 0.5       ])

In [12]:
v

array([[-0.93632918,  0.70710678],
       [-0.35112344, -0.70710678]])

In [ ]:
#3. 運用上列array計算SVD?

In [13]:
u, s, vh = np.linalg.svd(array2)
u

array([[-0.6690722 ,  0.74319741],
       [ 0.74319741,  0.6690722 ]])

In [14]:
s

array([0.53643143, 0.07169889])

In [15]:
vh

array([[-0.39971796,  0.91663818],
       [ 0.91663818,  0.39971796]])